# Generated by Django 4.2.13 on 2024-05-22 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financialProducts', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('nickname', models.CharField(max_length=20)),
                ('age', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('남성', '남성'), ('여성', '여성')], max_length=2)),
                ('salary', models.CharField(choices=[('0~3000만원 미만', '0~3000만원 미만'), ('3000~6000만원 미만', '3000~6000만원 미만'), ('6000~1억미만', '6000~1억미만'), ('1억 이상', '1억 이상')], max_length=100000)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='joinedProducts',
            field=models.ManyToManyField(blank=True, related_name='User', to='financialProducts.depositproducts'),
        ),
    ]
